site_name: COMPASS CTF
site_url: https://lyther.github.io/wiki/

theme:
  name: material

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: logo