site_name: COMPASS CTF Wiki
site_url: https://lyther.github.io/wiki/
site_description: Wiki project for COMPASS CTF, for usage of information sharing, collection, and reference. The contents are contributed by the students of COMPASS CTF team.
copyright: COMPASS & SUSTech 2021 CTF team

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  palette:
    primary: white
    accent: cyan
    scheme: preference
  icon:
    logo: logo

nav:
- Abstract:
  - index.md
- Book:
  - Computer and System:
    - Book/Computer and System/Android Dalvik虚拟机结构及机制剖析.md
    - Book/Computer and System/Android Internals.md
    - Book/Computer and System/Android系统源代码情景分析.md
    - Book/Computer and System/Code.md
    - Book/Computer and System/Computer Systems.md
    - Book/Computer and System/Linux Kernel Development.md
    - Book/Computer and System/Mac OS X and iOS Internals.md
    - Book/Computer and System/Understanding the Linux Kernel.md
    - Book/Computer and System/Windows Internals.md
    - Book/Computer and System/代码揭秘.md
    - Book/Computer and System/深入理解Android内核设计思想.md
  - Cryptography:
    - Book/Cryptography/Foundations of Cryptography.md
    - Book/Cryptography/Introduction to Modern Cryptography.md
    - Book/Cryptography/Understanding Cryptography.md
    - Book/Cryptography/图解密码技术.md
  - Network:
    - Book/Network/Computer Networking.md
    - Book/Network/Practical Packet Analysis.md
    - Book/Network/TCP IP Illustrated.md
- Tool:
  - Cryptography:
    - Tool/Cryptography/SageMathCell.md
  - Reverse Engineering:
    - Tool/Reverse Engineering/Bytecode Viewer.md
    - Tool/Reverse Engineering/DiE.md
    - Tool/Reverse Engineering/ExeInfoPE.md
- Tutorial:
  - CS315:
    - Tutorial/CS315/Overview.md
    - Tutorial/CS315/Week 1.md
    - Tutorial/CS315/Week 2.md
    - Tutorial/CS315/Week 3.md
  - Material:
    - Tutorial/Material/OS.md
    - Tutorial/Material/Network.md
    - Tutorial/Material/Cryptography.md
  - Schedule:
    - Tutorial/Schedule/Summer.md
- Website:
  - Forum:
    - Website/Forum/kanxue.md
  - Platform:
    - Website/Platform/Cryptopals.md
    - Website/Platform/CTFHub.md
    - Website/Platform/CTFlearn.md
    - Website/Platform/ctftime.md
    - Website/Platform/ichunqiu.md
    - Website/Platform/picoCTF.md
    - Website/Platform/pwnabletw.md
    - Website/Platform/TryHackMe.md
    - Website/Platform/World of Attack&Defense.md
  - Tutorial:
    - Website/Tutorial/CTF Field Guide.md
    - Website/Tutorial/CTF Wiki.md
    - Website/Tutorial/ctf101.md
    - Website/Tutorial/how to become a hacker.md
    - Website/Tutorial/linux.md
    - Website/Tutorial/python.md
- Writeup:
  - Binary Exploitation:
    - Writeup/Binary Exploitation/beginner-generic-pwn-number-0.md
    - Writeup/Binary Exploitation/collision.md
    - Writeup/Binary Exploitation/fd.md
    - Writeup/Binary Exploitation/printf-please.md
    - Writeup/Binary Exploitation/ret2generic-flag-reader.md
    - Writeup/Binary Exploitation/ret2the-unknown.md
    - Writeup/Binary Exploitation/simultaneity.md
  - Cryptography:
    - Writeup/Cryptography/Dachshund Attacks.md
    - Writeup/Cryptography/MedicalImage.md
    - Writeup/Cryptography/scissor.md
  - Forensics:
    - Writeup/Forensics/Disk, disk, sleuth! II.md
    - Writeup/Forensics/Disk, disk, sleuth!.md
    - Writeup/Forensics/MacroHard WeakEdge.md
    - Writeup/Forensics/Milkslap.md
    - Writeup/Forensics/Wireshark doo dooo do doo.md
  - General Skills:
    - Writeup/General Skills/2Warm.md
    - Writeup/General Skills/Lets Warm Up.md
  - Reverse Engineering:
    - Writeup/Reverse Engineering/bread-making.md
    - Writeup/Reverse Engineering/dimensionality.md
    - Writeup/Reverse Engineering/Shop.md
    - Writeup/Reverse Engineering/speeds and feeds.md
    - Writeup/Reverse Engineering/wstrings.md
  - Web Exploitation:
    - Writeup/Web Exploitation/Cookies.md
    - Writeup/Web Exploitation/inspect-me.md
    - Writeup/Web Exploitation/It is my Birthday.md
    - Writeup/Web Exploitation/Most Cookies.md
    - Writeup/Web Exploitation/Scavenger Hunt.md
