site_name: COMPASS CTF Wiki
site_url: https://lyther.github.io/wiki/
site_description: Wiki project for COMPASS CTF, for usage of information sharing, collection, and reference. The contents are contributed by the students of COMPASS CTF team.
copyright: COMPASS & SUSTech 2021 CTF team

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  palette:
    primary: white
    accent: cyan
    scheme: preference
  icon:
    logo: logo

nav:
- Abstract:
  - index.md
- Tutorial:
  - Material:
    - Tutorial/Material/OS.md
  - Schedule:
    - Tutorial/Schedule/Summer.md
- Website:
  - Forum:
    - Website/Forum/kanxue.md
  - Platform:
    - Website/Platform/CTFHub.md
    - Website/Platform/CTFlearn.md
    - Website/Platform/ctftime.md
    - Website/Platform/ichunqiu.md
    - Website/Platform/picoCTF.md
    - Website/Platform/pwnabletw.md
    - Website/Platform/TryHackMe.md
    - Website/Platform/World of Attack&Defense.md
  - Tutorial:
    - Website/Tutorial/CTF Field Guide.md
    - Website/Tutorial/CTF Wiki.md
    - Website/Tutorial/ctf101.md
    - Website/Tutorial/how to become a hacker.md
    - Website/Tutorial/linux.md
    - Website/Tutorial/python.md
- Writeup:
  - Binary Exploitation:
    - Writeup/Binary Exploitation/beginner-generic-pwn-number-0.md
    - Writeup/Binary Exploitation/collision.md
    - Writeup/Binary Exploitation/fd.md
    - Writeup/Binary Exploitation/printf-please.md
    - Writeup/Binary Exploitation/ret2generic-flag-reader.md
    - Writeup/Binary Exploitation/ret2the-unknown.md
    - Writeup/Binary Exploitation/simultaneity.md
  - Cryptography:
    - Writeup/Cryptography/Dachshund Attacks.md
    - Writeup/Cryptography/scissor.md
  - Forensics:
    - Writeup/Forensics/Disk, disk, sleuth! II.md
    - Writeup/Forensics/Disk, disk, sleuth!.md
    - Writeup/Forensics/MacroHard WeakEdge.md
    - Writeup/Forensics/Milkslap.md
    - Writeup/Forensics/Wireshark doo dooo do doo.md
  - General Skills:
    - Writeup/General Skills/2Warm.md
    - Writeup/General Skills/Lets Warm Up.md
  - Reverse Engineering:
    - Writeup/Reverse Engineering/bread-making.md
    - Writeup/Reverse Engineering/dimensionality.md
    - Writeup/Reverse Engineering/Shop.md
    - Writeup/Reverse Engineering/speeds and feeds.md
    - Writeup/Reverse Engineering/wstrings.md
  - Web Exploitation:
    - Writeup/Web Exploitation/Cookies.md
    - Writeup/Web Exploitation/inspect-me.md
    - Writeup/Web Exploitation/It is my Birthday.md
    - Writeup/Web Exploitation/Most Cookies.md
    - Writeup/Web Exploitation/Scavenger Hunt.md
